### ISSUE TITLE
Cannot set_fact to data_disk_devices when merging uuid

### ISSUE THREAD

**Issue by edlevin6612** [dragomirr/ansible-role-data-disk#1]
Ran into an issue with

```
- name: Combine data disk devices with uuid
  ansible.builtin.set_fact:
    data_disk_devices: "{{ data_disk_devices | community.general.lists_mergeby(data_disk__fact_uuid, 'device') }}"
  when: not data_disk_mount_by_device_name | bool
```
where `data_disk_devices` was not being updated due fact precedence mentioned in https://stackoverflow.com/a/30134080

Worked around by using an alternate fact name.

Using Ansible 2.17
